### ISSUE TITLE
Error in yarn start

### ISSUE THREAD

**Issue by pjavier1988** [qgis/qwc2-demo-app#85]
Hi.
Im working on Ubuntu 16.04, installed nodejs 9 and yarn 1.5.1
Im getting this error when I execute yarn start

`yarn run v1.5.1
$ npm run tsupdate && npm run themesconfig && webpack-dev-server --progress --colors --port 8081

> QWC2App@0.3.0 tsupdate /home/dotblock/qwc2-demo-app
> node qwc2/scripts/updateTranslations.js

Wrote qwc2/translations/data.pt-BR
Wrote translations/data.pt-BR
Wrote qwc2/translations/data.de-DE
Wrote translations/data.de-DE
Wrote qwc2/translations/data.en-US
Wrote translations/data.en-US
Wrote qwc2/translations/data.fr-FR
Wrote translations/data.fr-FR
Wrote qwc2/translations/data.it-IT
Wrote translations/data.it-IT
Wrote qwc2/translations/data.ro-RO
Wrote translations/data.ro-RO
Wrote qwc2/translations/data.sv-SE
Wrote translations/data.sv-SE

> QWC2App@0.3.0 themesconfig /home/dotblock/qwc2-demo-app
> node qwc2/scripts/themesConfig.js

/home/dotblock/qwc2-demo-app/node_modules/deasync/index.js:71
		process._tickDomainCallback();
		        ^

TypeError: process._tickDomainCallback is not a function
    at Function.module.exports.loopWhile (/home/dotblock/qwc2-demo-app/node_modules/deasync/index.js:71:11)
    at /home/dotblock/qwc2-demo-app/node_modules/deasync/index.js:44:19
    at Object.<anonymous> (/home/dotblock/qwc2-demo-app/qwc2/scripts/themesConfig.js:20:37)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! QWC2App@0.3.0 themesconfig: `node qwc2/scripts/themesConfig.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the QWC2App@0.3.0 themesconfig script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-01T03_17_41_819Z-debug.log
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh`

**Comment by manisandro** [comment]
There are various hits for `TypeError: process._tickDomainCallback is not a function` on google, please have a look if one of those applies to your situation. In any event, this is not a qwc2 issue.
